name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/gh-pages.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: 📦 Install Dependencies
        working-directory: docs
        run: pnpm install --frozen-lockfile

      - name: 🌌 Build Valaxy Docs
        working-directory: docs
        run: pnpm build

      - name: 🪤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          cname: sts2-ritsulib.ritsukage.com
          force_orphan: true
